Adds pixel data check on input data. Exits success if no pixel data present
scitran-apps/dcm2niix pull request #7
Opened 2017-08-09 18:44 UTC by jenreiter

Fixes #6 

Overview of change:
- A dicom "reader" was added to the Dockerfile in order to inspect the dicom to determine if pixel data is present
- Every file within the unzipped directory is checked for pixel data, if ANY one of those files does not contain the PixelData DICOM tag, dcm2niix is not executed and exits with a 0 returncode

Testing:
- Ran the gear on zipped T1 images and dcm2niix ran successfully and produced an output file
- Ran the gear on zipped PhoenixZipReport files (does not contain DICOM tag PixelData) and dcm2niix did not execute, returned a 0 exit code and did not produce any outputs.

2017-08-11 21:00 UTC, lmperry approved these changes
LGTM, however it's unclear how this will handle the NON-DICOM case (i.e. PAR-REC).

2017-08-11 21:08 UTC, lmperry requested changes
On second look, please test with PAR/REC files. dicomdump will error on not being able to read them. You'll need to modify to be able to work with those.

2017-08-11 22:08 UTC, neurolabusc commented
Why not use the return value generated by dcm2niix itself. This should be zero (EXIT_SUCCESS) if successful, and any other value indicates that conversion was unsuccessful. Consider the following shell script:

```
#!/bin/bash
./dcm2niix -f %p_%s ~/book/dcm
echo "success $?"
./dcm2niix -f %p_%s ~/book/nodcm
echo "success $?"
./dcm2niix -f %p_%s ~/book/parrec/a.par
echo "success $?"
```
It generates

```
>./return_codes.bat
Chris Rorden's dcm2niiX version v1.0.20170724 GCC6.1.0 (64-bit MacOS)
Found 5 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
Convert 5 DICOM as /Users/rorden/book/dcm/BOLD_AP_BIC_Driving_5 (108x108x70x5)
Conversion required 0.100083 seconds (0.085991 for core code).
success 0
Chris Rorden's dcm2niiX version v1.0.20170724 GCC6.1.0 (64-bit MacOS)
Error: Unable to find any DICOM images in /Users/rorden/book/nodcm
success 1
Chris Rorden's dcm2niiX version v1.0.20170724 GCC6.1.0 (64-bit MacOS)
Done reading PAR header version 4.2, with 70 volumes
Warning: Reported TR=4700.39ms, measured TR=4612.32ms (prospect. motion corr.?)
Converting XYTZ to XYZT with 29 slices (Z) and 70 volumes (T).
Convert 1 DICOM as /Users/rorden/book/parrec/WIPpCASLSENSE4.2_5 (64x64x29x70)
Philips Precise RS:RI:SS = 1.2442:0:0.0140355 (see PMC3998685)
 R = raw value, P = precise value, D = displayed value
 RS = rescale slope, RI = rescale intercept,  SS = scale slope
 D = R * RS + RI    , P = D/(RS * SS)
 D scl_slope:scl_inter = 1.2442:0
 P scl_slope:scl_inter = 71.2479:0
 Using P values ('-p n ' for D values)
Conversion required 0.423215 seconds (0.400146 for core code).
success 0
```

This should be faster than running both a reader and a separate reader program (as it does everything in one pass) and it should be more accurate (e.g. consider a file with pixel data that uses an unsupported transfer syntax).

2017-08-11 22:30 UTC, neurolabusc commented
Can you try the latest master of dcm2niix - I have added a feature so the software returns EXIT_SUCCESS (0) if files are created, EXIT_FAILURE (1) if there is a problem, and 2 if no valid files were detected. This allows software to discriminate between these two situations where files are not generated.

2017-08-11 22:33 UTC, lmperry commented
Hi @neurolabusc (Chris)! Thanks for your comment (I owe you some example data for #4 - I haven't forgotten). 

We do respect the exit status (https://github.com/scitran-apps/dcm2niix/blob/master/run#L139-L142) and I should say that I do agree with you in principle about exit status (IMO it should exit 1 as the purpose of this gear is to convert X to NIfTI). However, we automatically run this Gear on every set of DICOMs that come off of our scanner and the issue is that when it encounters a set of DICOMs that don't contain pixel data (e.g., SIEMENS Phoenix Zip Reports) and it exits 1 we're notified that there was a failure and our job records forever reflect that failure state (we do keep them in our DB forever). In this case we don't necessarily want to be notified as we never expected it to succeed on these types of data. 

That being said, it would be great to have an exit status that essentially represents 'this is a valid DICOM series but there's nothing to do', to disambiguate the cases where there is truly an error. 

I also share your concern over speed of reading each dicom file - that could be a real issue when there are series with 1000's of files... more testing required.

2017-08-11 22:40 UTC, neurolabusc commented
@lmperry - I do think it would be nice to have in the core program, as other tools are likely to have this issue. I am pretty sure the patch I added a few minutes ago will not do precisely what you want - the Phoenix reports are DICOM files even if they are not DICOM images. Would you be able to share a couple with me and I can make the DICOM detection a bit more robust.

2017-08-11 22:51 UTC, neurolabusc commented
@lmperry - I have pushed another update that should generate return code 2 whenever no convertible files are found. Please test, but I think this will correctly detect that your Phoenix reports are not pixel data.

2017-08-17 22:21 UTC, lmperry commented
Thanks! @neurolabusc your modifications worked to correctly detect when a "non-image" DICOM series is present and $?=2. I have another PR #8 which respects this new behavior. I also now build dcm2niix from source with openjpeg support (additional comments on that PR).

2017-08-17 22:21 UTC, closed without merging